
package entity;

import lombok.Data;
import org.json.JSONObject;

@Data
public class Client implements JSONableEntity {

    // ========================================================================================
    // Fields
    // ========================================================================================

    private String name;
    private String email;
    private String shippingAddress;
    private String phone;

    // ========================================================================================
    // Constructors
    // ========================================================================================

    public Client(String name, String email, String shippingAddress, String phone) {
        this.name = name;
        this.email = email;
        this.shippingAddress = shippingAddress;
        this.phone = phone;
    }

    public Client() {
    }

    // ========================================================================================
    // Getters & Setters
    // ========================================================================================

    // generated by lombok

    // ========================================================================================
    // Methods
    // ========================================================================================

    public JSONObject toJSON(String mvRecordAction) {
        JSONObject mvSupplierClient = createJSONObjectFromThis();

        JSONObject container = new JSONObject();
        container.put("mvSupplierClient", mvSupplierClient);
        container.put("mvRecordAction", mvRecordAction);

        return container;
    }

    private JSONObject createJSONObjectFromThis() {
        JSONObject mvSupplierClient = new JSONObject();

        mvSupplierClient.put("SupplierClientName", this.getName());
        mvSupplierClient.put("SupplierClientEmail", this.getEmail());
        mvSupplierClient.put("SupplierClientShippingAddress1", this.getShippingAddress());
        mvSupplierClient.put("SupplierClientPhone1", this.getPhone());
        return mvSupplierClient;
    }

}
