

package entity;

import lombok.Data;
import org.json.JSONObject;

@Data
public class InventoryLocation implements Item  {

    // ========================================================================================
    // Fields
    // ========================================================================================

    private String abbreviation;
    private String name;
    private String address;

    // ========================================================================================
    // Constructors
    // ========================================================================================

    public InventoryLocation(String abbreviation, String name, String address) {
        this.abbreviation = abbreviation;
        this.name = name;
        this.address = address;
    }

    public InventoryLocation() {
    }

    // ========================================================================================
    // Getters & Setters
    // ========================================================================================

    // generated by lombok

    // ========================================================================================
    // Methods
    // ========================================================================================

    public JSONObject toJSON(String mvRecordAction) {
        //  creating the json object
        JSONObject json = new JSONObject();

//        Insert action
        json.put("mvRecordAction", mvRecordAction);

//        creating the product details
        JSONObject mvLocation = new JSONObject();

        mvLocation.put("InventoryLocationAbbreviation", this.getAbbreviation());
        mvLocation.put("InventoryLocationName", this.getName());
        mvLocation.put("InventoryLocationAddress", this.getAddress());

//        add product details to final json
        json.put("mvInventoryLocation", mvLocation);

        return json;
    }

}
