

package entity;

import lombok.Data;
import org.json.JSONObject;

@Data
public class InventoryLocation implements JSONableEntity {

    // ========================================================================================
    // Fields
    // ========================================================================================

    private String abbreviation;
    private String name;
    private String address;

    // ========================================================================================
    // Constructors
    // ========================================================================================

    public InventoryLocation(String abbreviation, String name, String address) {
        this.abbreviation = abbreviation;
        this.name = name;
        this.address = address;
    }

    public InventoryLocation() {
    }

    // ========================================================================================
    // Getters & Setters
    // ========================================================================================

    // generated by lombok

    // ========================================================================================
    // Methods
    // ========================================================================================

    public JSONObject toJSON(String mvRecordAction) {
        JSONObject mvLocation = createJSONObjectFromThis();

        JSONObject container = new JSONObject();
        container.put("mvRecordAction", mvRecordAction);
        container.put("mvInventoryLocation", mvLocation);

        return container;
    }

    private JSONObject createJSONObjectFromThis() {
        JSONObject mvLocation = new JSONObject();

        mvLocation.put("InventoryLocationAbbreviation", this.getAbbreviation());
        mvLocation.put("InventoryLocationName", this.getName());
        mvLocation.put("InventoryLocationAddress", this.getAddress());
        return mvLocation;
    }

}
