
package entity;


import lombok.Data;
import org.json.JSONObject;

@Data
public class Product implements Item {

    // ========================================================================================
    // Fields
    // ========================================================================================

    private int SKU;
    private String description;
    private double salesPrice;
    private double purchasePrice;

    // ========================================================================================
    // Constructors
    // ========================================================================================

    public Product(int SKU, String description, double salesPrice, double purchasePrice) {
        this.SKU = SKU;
        this.description = description;
        this.salesPrice = salesPrice;
        this.purchasePrice = purchasePrice;
    }

    public Product() {
    }


    // ========================================================================================
    // Getters & Setters
    // ========================================================================================

    // generated by lombok

    // ========================================================================================
    // Methods
    // ========================================================================================

    public JSONObject toJSON(String mvRecordAction) {
        //      creating the json object
        JSONObject json = new JSONObject();

//        Insert action
        json.put("mvRecordAction", mvRecordAction);

//        creating the product details
        JSONObject mvProduct = new JSONObject();

        mvProduct.put("ProductSKU", this.getSKU());
        mvProduct.put("ProductDescription", this.getDescription());
        mvProduct.put("ProductSellingPrice", String.valueOf(this.getSalesPrice()));
        mvProduct.put("ProductPurchasePrice", String.valueOf(this.getPurchasePrice()));

//        add product details to final json
        json.put("mvProduct", mvProduct);

        return json;
    }

}
