/**
 * Part of MegaventoryApplication
 * Created by: @Author V
 * Date: @Date 24-Jun-22
 * Time: 11:31
 * =============================================================
 **/

package entity;

import lombok.Data;
import org.json.JSONObject;

@Data
public class SaleOrderDetails implements JSONableEntity {

    // ========================================================================================
    // Fields
    // ========================================================================================

    private String productSKU;
    private int productQuantity;
    private int taxID;
    private int discountID;


    // ========================================================================================
    // Constructors
    // ========================================================================================


    public SaleOrderDetails(String productSKU, int productQuantity, int taxID, int discountID) {
        this.productSKU = productSKU;
        this.productQuantity = productQuantity;
        this.taxID = taxID;
        this.discountID = discountID;
    }

    public SaleOrderDetails() {
    }

    // ========================================================================================
    // Getters & Setters
    // ========================================================================================

    // generated by lombok

    // ========================================================================================
    // Methods
    // ========================================================================================

    @Override
    public JSONObject toJSON(String mvRecordAction) {
        return  createJSONObjectFromThis();
    }

    private JSONObject createJSONObjectFromThis() {
        JSONObject saleDetails = new JSONObject();

        saleDetails.put("SalesOrderRowProductSKU", getProductSKU());
        saleDetails.put("SalesOrderRowQuantity", String.valueOf(getProductQuantity()));
        saleDetails.put("SalesOrderRowTaxID", String.valueOf(getTaxID()));
        saleDetails.put("SalesOrderRowDiscountID", String.valueOf(getDiscountID()));

        return saleDetails;
    }

}
