
package entity;

import lombok.Data;
import org.json.JSONObject;

@Data
public class Tax implements Item  {

    // ========================================================================================
    // Fields
    // ========================================================================================

    private String name;
    private String description;
    private double value;

    // ========================================================================================
    // Constructors
    // ========================================================================================

    public Tax(String name, String description, double value) {
        this.name = name;
        this.description = description;
        this.value = value;
    }

    public Tax() {
    }

    // ========================================================================================
    // Getters & Setters
    // ========================================================================================

    // generated by lombok

    // ========================================================================================
    // Methods
    // ========================================================================================

    public JSONObject toJSON(String mvRecordAction) {
        // creating the json object
        JSONObject json = new JSONObject();

        // Insert action
        json.put("mvRecordAction", mvRecordAction);

        // creating the product details
        JSONObject mvTax = new JSONObject();

        mvTax.put("TaxName", this.getName());
        mvTax.put("TaxDescription", this.getDescription());
        mvTax.put("TaxValue", String.valueOf(this.value));

        // dd product details to final json
        json.put("mvTax", mvTax);

        return json;
    }

}
